name: ERC-2280 CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install Yarn Globally
              run: npm install -g yarn@1.22.4

            - name: Install dependencies
              run: yarn install

            - name: Run Editorconfig checks
              run: yarn test:editorconfig

            - name: Run SolHint checks
              run: yarn test:lint

            - name: Run Truffle test suite
              run: yarn test:coverage

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.github_token }}
